### ISSUE TITLE
Feature request: flag to download closed issues

### ISSUE THREAD

**Issue by seanriceaz** [Tallwave/github_issue_exporter#7]
Would be nice to be able to get closed issues too for archival purposes.

**Comment by swilliams** [comment]
Looks like you can pass in a parameter that gets all issues.

**Comment by seanriceaz** [comment]
@swilliams What is the flag? It's not in the documentation. Or I should say, not in readme.md

**Comment by swilliams** [comment]
Oh, it's in the GitHub API. It would need to be implemented here.

**Comment by swilliams** [comment]
Implemented :fireworks:

**Comment by seanriceaz** [comment]
Seems partially implemented. I just tested this in a repo that has over 128 issues.
I was able to get issues (even closed ones) back to #128. 
But the rest were mysteriously dropped.
